# gimme_ai/templates/wrangler.toml
name = "{{ project_name }}"
main = "worker.js"
compatibility_date = "2024-12-27"

# Durable Objects bindings
[[durable_objects.bindings]]
name = "IP_LIMITER"
class_name = "IPRateLimiter"

[[durable_objects.bindings]]
name = "GLOBAL_LIMITER"
class_name = "GlobalRateLimiter"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["IPRateLimiter", "GlobalRateLimiter"]

# Add workflow binding if project directory exists
{% if has_workflow %}
[[workflows]]
name = "{{ project_name }}"
binding = "{{ project_name | upper }}_WORKFLOW"
class_name = "{{ workflow_class_name }}"
{% endif %}

# Add environment variables
[vars]
MODAL_ENDPOINT = "{{ prod_endpoint }}"
{% for key in required_keys %}
{{ key }} = "${{{ key }}}"
{% endfor %}
{{ admin_password_env }} = "${{{ admin_password_env }}}"

# Documentation for environment variables
# These are set as secrets using wrangler secret put
{% for key in required_keys %}
# {{ key }} is available as env.{{ key }}
{% endfor %}
# {{ admin_password_env }} is available as env.{{ admin_password_env }}

# Security settings
[security]
# Ensure secrets are properly handled
allow_credentials_in_env = true

# Observability settings for logging
[observability]
enabled = {{ observability.enabled }}
head_sampling_rate = {{ observability.head_sampling_rate }}

{% if 'logs' in observability %}
[observability.logs]
invocation_logs = {{ observability.logs.invocation_logs }}
{% endif %}
