# gimme_ai/templates/wrangler.toml
name = "{{ project_name }}"
main = "worker.js"
compatibility_date = "2024-10-22"

# Durable Objects bindings
[[durable_objects.bindings]]
name = "IP_LIMITER"
class_name = "IPRateLimiter"

[[durable_objects.bindings]]
name = "GLOBAL_LIMITER"
class_name = "GlobalRateLimiter"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["IPRateLimiter", "GlobalRateLimiter"]

# Add workflow binding if workflow is enabled
{% if has_workflow %}
[[workflows]]
name = "{{ project_name }}-workflow"
binding = "{{ project_name | upper | replace('-', '_') }}_WORKFLOW"
class_name = "{{ workflow_class_name }}"
{% endif %}

# Add environment variables
[vars]
MODAL_ENDPOINT = "{{ prod_endpoint }}"

# Documentation for environment variables
# These are set as secrets using wrangler secret put
{% for key in required_keys %}
# {{ key }} is available as env.{{ key }}
{% endfor %}
# {{ admin_password_env }} is available as env.{{ admin_password_env }}

# Observability settings for logging
[observability]
enabled = {{ observability.enabled }}
head_sampling_rate = {{ observability.head_sampling_rate }}

{% if observability.logs is defined %}
[observability.logs]
invocation_logs = {{ observability.logs.invocation_logs }}
{% endif %}
