
# Minimal wrangler.toml for gimme-ai-test2
name = "gimme-ai-test2"
main = "worker.js"
compatibility_date = "2024-12-27"

# Durable Objects bindings
[[durable_objects.bindings]]
name = "IP_LIMITER"
class_name = "IPRateLimiter"

[[durable_objects.bindings]]
name = "GLOBAL_LIMITER"
class_name = "GlobalRateLimiter"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["IPRateLimiter", "GlobalRateLimiter"]

# Workflow binding
[[workflows]]
name = "gimme-ai-test2"
binding = "GIMME-AI-TEST2_WORKFLOW"
class_name = "GimmeAiTest2Workflow"

# Add environment variables
[vars]
MODAL_ENDPOINT = "https://gimme-ai-test2.modal.run"
MODAL_TOKEN_ID = "${{ MODAL_TOKEN_ID }}"
MODAL_TOKEN_SECRET = "${{ MODAL_TOKEN_SECRET }}"
GIMME_ADMIN_PASSWORD = "${{ GIMME_ADMIN_PASSWORD }}"
